name: Publish site
on: push

jobs: 
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Push directory to another repository
              uses: johnnycrich/github-action-push-to-another-repository@master
              env:
                API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
              with:
                source-directory: '__sapper__/export'
                destination-github-username: 'johnnycrich'
                destination-repository-name: 'johnnycrich.github.io'
                user-email: johnny.c.rich@gmail.com
                target-branch: 'main'
